-- AlterTable: add per-user daily goals (defaults mirror previously hardcoded targets)
ALTER TABLE "User" ADD COLUMN "calGoal" INTEGER NOT NULL DEFAULT 2350;
ALTER TABLE "User" ADD COLUMN "protGoal" INTEGER NOT NULL DEFAULT 160;
ALTER TABLE "User" ADD COLUMN "carbGoal" INTEGER NOT NULL DEFAULT 245;
ALTER TABLE "User" ADD COLUMN "fatGoal" INTEGER NOT NULL DEFAULT 65;
ALTER TABLE "User" ADD COLUMN "stepGoal" INTEGER NOT NULL DEFAULT 8000;
